version: '3.9'

services:

  db:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/despensa_postgres/test_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: despensa_pass